name: Android Instrumented Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  instrumented-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: google_apis
          arch: x86_64
          script: ./gradlew :app:connectedDebugAndroidTest

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: instrumented-test-reports
          path: '**/build/reports/androidTests'
